name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 配置软件环境
      run: | 
        sudo apt-get update
        curl -fsSL https://xmake.io/shget.text | bash
        sudo apt-get install clang clang++ build-essential git gcc g++ make cmake
        sudo apt-get upgrade
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27
      